---
name: "HideEmptyFolders"
guid: "e3a1b2c4-1234-5678-9abc-def012345678"
version: "1.0.0.2"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Automatically manages .ignore files to hide empty folders from Jellyfin library views"
description: >
  This plugin automatically scans configured media directories and manages .ignore files
  based on video content presence. For directories containing video files (including in
  subdirectories like TV show seasons), it removes .ignore files to make them visible.
  For directories without video content, it creates .ignore files to hide them from
  library views. Supports multiple scan directories, configurable video extensions,
  and customizable scan intervals.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.HideEmptyFolders.dll"
changelog: >
  v1.0.0.0: Initial release with recursive video scanning, multiple folder support,
  and automatic .ignore file management for cleaner library organization.
