name: '📝 Create/Update Release Draft & Release Bump PR'

on:
  push:
    branches:
      - master
    paths-ignore:
      - build.yaml
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-prep-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@8eed318e74aed0a7cc41de6dafd36eb693a1f6fc # master
    with:
      repository-name: jellyfin/jellyfin-plugin-template
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
