# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@2d1d8651c878e11ce83de5ecdbedb31e70ebc6f0 # master
    secrets:
      token: .
