name: "🚀 Publish Plugin"

on:
  release:
    types:
      - released
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Clean
        run: dotnet clean
      - name: Build Dotnet
        run: dotnet build --no-restore --warnaserror
      - name: "Flag as nightly in build.yaml"
        uses: fjogeleit/yaml-update-action@04ff6ec06568fd21197db746472e36cc425de850 # v0.16.1
        with:
          valueFile: "build.yaml"
          propertyPath: "version"
          value: "${{ github.event.release.tag_name }}"
          commitChange: false
          updateFile: true

      - name: "JPRM: Build"
        uses: oddstr13/jellyfin-plugin-repository-manager@9497a0a499416cc572ed2e07a391d9f943a37b4d # v1.1.1
        id: jprm
        with:
          version: "${{ github.event.release.tag_name }}"
          dotnet-target: "net8.0"
          output: _dist

      - name: Prepare GitHub Release assets
        run: |-
          pushd _dist
          for file in ./*.zip; do
            md5sum ${file#./} >> ${file%.*}.md5
            sha256sum ${file#./} >> ${file%.*}.sha256
          done
          ls -l
          popd
      - name: Publish output artifacts
        id: publish-assets
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            _dist/*
            build.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Plugin Manifest
        uses: Kevinjil/jellyfin-plugin-repo-action@296850372cd569cbcc040e834222a5afed861485
        with:
          ignorePrereleases: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pagesBranch: manifests
          pagesFile: manifest.json
