name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  call:
    permissions:
      issues: write
      pull-requests: write
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@8eed318e74aed0a7cc41de6dafd36eb693a1f6fc # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
