name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  call:
    permissions:
      issues: write
      pull-requests: write
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@8264ba0b1dd1c2a45202ae88c0191c460e1fa3ea # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
