name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  call:
    permissions:
      issues: write
      pull-requests: write
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@76479344f979ced7a83b032fbe67fd5e7a3ce00e # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
